build:
  environment:
    python: 3.6.3
  dependencies:
    before:
      - pip install -U pip wheel setuptools
      - pip install psycopg2 mysqlclient python-coveralls codecov
      - pip install --process-dependency-links -e ".[testing]"
  tests:
    override:
      - py.test

checks:
  python:
    code_rating: true
    duplicate_code: true

filter:
  excluded_paths:
    - kotti/tests/
    - kotti/alembic/
