build:
  environment:
    python: 3.6.3
  dependencies:
    before:
      - pip install -U pip wheel setuptools
      - pip install psycopg2 mysqlclient python-coveralls codecov
      - wget https://github.com/disko/deform/archive/2.0.5.dev0.zip#egg=deform-2.0.5.dev0 && pip install 2.0.5.dev0.zip
      - pip install -e .[testing]
  tests:
    override:
      - command: pytest
        coverage:
          file: '.coverage'
          config_file: '.coveragerc'
          format: 'py-cc'

checks:
  python:
    code_rating: true
    duplicate_code: true

filter:
  excluded_paths:
    - kotti/tests/
    - kotti/alembic/
