# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
dependencies:
  override:
    - pip install tox tox-pyenv
    - pyenv local 3.6.4 3.5.4
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:10.1
      # - image: circleci/postgres:9.6
      - image: circleci/mysql:8

    working_directory: ~/kotti

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip wheel setuptools setuptools-git
            pip install psycopg2 mysqlclient python-coveralls codecov
            pip install --process-dependency-links -e .[testing]

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test

      - store_artifacts:
          path: test-reports
          destination: test-reports
